
<div id="carousel-305709" class="carousel slide">
	<ol class="carousel-indicators">
		<li class="active" data-target="#carousel-305709" data-slide-to="0">
		</li>
		<li data-target="#carousel-305709" data-slide-to="1">
		</li>
		<li data-target="#carousel-305709" data-slide-to="2">
		</li>
	</ol>
	<div class="carousel-inner">
		<div class="item active">
			<img alt="" src="<?php echo $this->basePath('img/slide1.jpg') ?>" />
		</div>
		<div class="item">
			<img alt="" src="<?php echo $this->basePath('img/slide2.jpg') ?>" />
		</div>
		<div class="item">
			<img alt="" src="<?php echo $this->basePath('img/slide3.jpg') ?>" />
		</div>
	</div> <a class="left carousel-control" href="#carousel-305709" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-305709" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
<p style="font-size:2.2em"><b>Rankpleo</b> es un lugar para compartir experiencias dentro del mundo laboral,
ya sea para que b&uacute;sques informaci&oacute;n sobre una oferta de empleo o
simplemente quieres decir que tan increible es tu lugar de trabajo...</p>
