<?php
	$form->setAttribute('action', $this->url('login', array('action' => 'register')));
	$form->prepare();

	echo $this->form()->openTag($form);
?>

<div class="row clearfix">
	<div class="col-md-4 column">
	</div>
	<div class="col-md-4 column">
		<span class="text-center">
		</span>
		<div class="panel panel-default">
			<div class="panel-heading" style="text-align: center;">
				<h3 class="panel-title">Registro</h3>
			</div>
			<div class="panel-body">
				<div class="form-group">
					<?php echo $this->formRow($form->get('txtName')); ?>
				</div>
				<div class="form-group">
					<?php echo $this->formRow($form->get('txtPaterno')); ?>
				</div>
				<div class="form-group">
					<?php echo $this->formRow($form->get('txtEmail')); ?>
				</div>
				<div class="form-group">
					<?php echo $this->formRow($form->get('txtPass')); ?>
				</div>
				<div class="form-group">
					<?php echo $this->formRow($form->get('txtConfirmPass')); ?>
				</div>
			</div>
			<div class="panel-footer text-center">
				<button class="btn btn-default btn-lg btn-block"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;&nbsp;Registrar</button>
			</div>
			<center>
				<p style="color: red;"><?php echo $this->message; ?></p>
			</center>
		</div>
	</div>
	<div class="col-md-4 column">
	</div>
</div>

<?php

	echo $this->form()->closeTag();