<h2>Agregar empresa</h2>
<form role="form">
	<div class="form-group">
		<label for="name">Nombre</label>
		<input id="name" class="form-control" type="textbox" />
	</div>
	<div class="form-group">
		 <label for="address">Domicilio</label>
		 <input id="address" class="form-control" type="textbox" />
	</div>
	<div class="form-group">
		 <label for="city">Ciudad</label>
		 <input id="city" class="form-control" type="textbox" />
	</div>
	<div class="form-group">
		 <label for="state">Estado</label>
		 <input id="state" class="form-control" type="textbox" />
	</div>
	<div class="form-group">
		 <label for="address">Domicilio</label>
		 <input id="address" class="form-control" type="textbox" />
	</div>
	<div class="form-group">
		 <label for="categoria">Categor&iacute;a</label><input id="categoria" type="textbos" />		
	</div>
	<div class="form-group">
		<label for="image">Agregar foto</label><input id="image" type="file" />
			<p class="help-block">
						Agregar imagen
			</p>
	</div>
	<button class="btn btn-default" type="submit">Guardar</button>
</form>


<?php

    echo count($resultado);

    foreach($resultado as $res)
    {
        print_r($res);
    }