<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    	<?php include_once($this->basePath() . '/analyticstracking.php'); ?>
        <nav class="navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo_rankpleo.png') ?>" alt="Rankpleo" width="140" height="123" /></a>
                </div>
                <div class="collapse navbar-collapse pull-right">
                    <ul class="nav navbar-nav">
			<li class="active"><a href="<?php echo $this->url('home') ?>">Inicio</a></li>
			<li><a href="<?php echo $this->url('login') ?>">M&aacute;s comentados</a></li>
			<li><a href="<?php echo $this->url('login') ?>">Mejor calificados</a></li>
			<li><a href="<?php echo $this->url('login') ?>">Mapa</a></li>
			<li><a href="<?php echo $this->url('login') ?>">Entrar</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
	    <?php echo $this->content; ?>
	   
	</div> <!-- /container -->
	<footer style="background-color:#4BA82C">
		<div class="container center-block" style="margin:0 200px; width:auto;"> 
			<div class="row"> 
				<div class="col-md-3 column text-center"><a href="#">Aviso de privacidad</a></div>
				<div class="col-md-3 column text-center"><a href="#">Terminos y Condiciones</a></div>
				<div class="col-md-3 column text-center"><a href="#">Contacto</a></div>
				<div class="col-md-3 column text-center"><a href="#">Acerca de</a></div>
			</div>		
		</div>
	</footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
