<div id="carousel-305709" class="carousel slide">
	<ol class="carousel-indicators">
		<li class="active" data-target="#carousel-305709" data-slide-to="0">
		</li>
		<li data-target="#carousel-305709" data-slide-to="1">
		</li>
		<li data-target="#carousel-305709" data-slide-to="2">
		</li>
	</ol>
	<div class="carousel-inner">
		<div class="item active">
			<img alt="" src="http://lorempixel.com/1600/500/sports/1" />
			<div class="carousel-caption">
				<h4>
					First Thumbnail label
				</h4>
				<p>
					Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
				</p>
			</div>
		</div>
		<div class="item">
			<img alt="" src="http://lorempixel.com/1600/500/sports/2" />
			<div class="carousel-caption">
				<h4>
					Second Thumbnail label
				</h4>
				<p>
					Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
				</p>
			</div>
		</div>
		<div class="item">
			<img alt="" src="http://lorempixel.com/1600/500/sports/3" />
			<div class="carousel-caption">
				<h4>
					Third Thumbnail label
				</h4>
				<p>
					Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
				</p>
			</div>
		</div>
	</div> <a class="left carousel-control" href="#carousel-305709" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-305709" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

